#!/usr/bin/perl 

use Getopt::Long qw(GetOptions);
use Cwd;

$baseurl = "https://danbooru.donmai.us/";
$pageurl = "posts?page=";
$tagsurl = "&tags=";
$tmplocation = "/usr/tmp/Danbooru/";
@maketmpdir = ("mkdir", "$tmplocation");
system `@maketmpdir`;
$tags = '';
$destination = getcwd();

GetOptions(
   'tags|t=s' => \$tags,
   'page|p=i{,2}' => \@pagenumber,
   'download|d' => \&download,
   'view|v' => \&view,
   'destination' => 
);

sub fix {
   if ($pagenumber[1] == undef){
      $pagenumber[1] = $pagenumber[0];
   }  
   if ($pagenumber[1] < $pagenumber[0]) {
      ($pagenumber[0], $pagenumber[1]) = ($pagenumber[1], $pagenumber[0]);
   }  
}

sub base {
   $fullurl = $baseurl.$pageurl.$pagenumber[1].$tagsurl.$tags;
   $textfile = $pageurl.$pagenumber[1].$tagsurl.$tags;
   @pagegrab = ("wget -q -o /dev/null -P \"$tmplocation\" \"$fullurl\""); 
   system `@pagegrab`;
   $tmpfile = $tmplocation.$textfile;
   @grepcommand = ("grep -oP 'data-large-file-url=\"/\\K[^\"]+' \"$tmpfile\"");
   chomp(@pictures = `@grepcommand`);
   return @pictures;
}

sub view {
   fix;
   $fehlist = $tags.".txt";
   $listpath = $tmplocation.$fehlist;
   @touchlist = ("touch", "$listpath");
   system `@touchlist`;
   system `@touchtmp`;
   while($pagenumber[1] >= $pagenumber[0]){
      base;
      @picrev = reverse(@pictures);
      foreach(@picrev){
         $pictureurl = $baseurl.$_;
         open my $in, '<', "$listpath" or die "ERROR: $!";  
         open my $out, '>', "$listpath.new" or die;  
         print $out "$pictureurl\n";
         while( <$in> ) {
            print $out $_;
         }  
         close $out;
         close $in;
         unlink($listpath);
         rename("$listpath.new", $listpath);
      }  
      $pagenumber[1]--;
   }
   @fehview = ("feh", "-f", $listpath, "-F");
   system `@fehview`
}

sub download {
   fix;
   while($pagenumber[1] >= $pagenumber[0]){
      base;
      foreach(@pictures){
         $pictureurl = $baseurl.$_;
         @downloadpictures = ("wget -P \"$destination\" \"$pictureurl\"");
         system `@downloadpictures`;
      }
      $pagenumber[1]--;
   }
}

@cleanup = ("rm -r \"$tmplocation\"");
system `@cleanup`;
